// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamDraft.Api.Data;

#nullable disable

namespace TeamDraft.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260321131924_AddEntityRelationships")]
    partial class AddEntityRelationships
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TeamDraft.Api.Entities.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<int?>("AssignedTeamId")
                        .HasColumnType("int");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Skill1")
                        .HasColumnType("int");

                    b.Property<int>("Skill2")
                        .HasColumnType("int");

                    b.Property<int>("Skill3")
                        .HasColumnType("int");

                    b.Property<int>("Skill4")
                        .HasColumnType("int");

                    b.HasKey("ParticipantId");

                    b.HasIndex("AssignedTeamId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.Pick", b =>
                {
                    b.Property<int>("PickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PickId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ParticipantId")
                        .HasColumnType("int");

                    b.Property<int>("PickOrder")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("PickId");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("TeamId");

                    b.ToTable("Picks");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<int>("LeaderUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("TeamId");

                    b.HasIndex("LeaderUserId")
                        .IsUnique();

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.Participant", b =>
                {
                    b.HasOne("TeamDraft.Api.Entities.Team", "AssignedTeam")
                        .WithMany("Participants")
                        .HasForeignKey("AssignedTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AssignedTeam");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.Pick", b =>
                {
                    b.HasOne("TeamDraft.Api.Entities.Participant", "Participant")
                        .WithMany("Picks")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamDraft.Api.Entities.Team", "Team")
                        .WithMany("Picks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.Team", b =>
                {
                    b.HasOne("TeamDraft.Api.Entities.User", "Leader")
                        .WithOne("Team")
                        .HasForeignKey("TeamDraft.Api.Entities.Team", "LeaderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.Participant", b =>
                {
                    b.Navigation("Picks");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.Team", b =>
                {
                    b.Navigation("Participants");

                    b.Navigation("Picks");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.User", b =>
                {
                    b.Navigation("Team");
                });
#pragma warning restore 612, 618
        }
    }
}
