// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamDraft.Api.Data;

#nullable disable

namespace TeamDraft.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("TeamDraft.Api.Entities.ParticipantProfile", b =>
                {
                    b.Property<int>("ParticipantProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ParticipantProfileId"));

                    b.Property<int?>("AssignedTeamId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsLeader")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Skill1")
                        .HasColumnType("int");

                    b.Property<int>("Skill2")
                        .HasColumnType("int");

                    b.Property<int>("Skill3")
                        .HasColumnType("int");

                    b.Property<int>("Skill4")
                        .HasColumnType("int");

                    b.Property<string>("Studies")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ParticipantProfileId");

                    b.HasIndex("AssignedTeamId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ParticipantProfiles");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.Pick", b =>
                {
                    b.Property<int>("PickId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PickId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ParticipantProfileId")
                        .HasColumnType("int");

                    b.Property<int>("PickOrder")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("PickId");

                    b.HasIndex("ParticipantProfileId");

                    b.HasIndex("TeamId");

                    b.ToTable("Picks");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<int>("LeaderUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("TeamId");

                    b.HasIndex("LeaderUserId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.ParticipantProfile", b =>
                {
                    b.HasOne("TeamDraft.Api.Entities.Team", "AssignedTeam")
                        .WithMany("Members")
                        .HasForeignKey("AssignedTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("TeamDraft.Api.Entities.User", "User")
                        .WithOne("ParticipantProfile")
                        .HasForeignKey("TeamDraft.Api.Entities.ParticipantProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTeam");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.Pick", b =>
                {
                    b.HasOne("TeamDraft.Api.Entities.ParticipantProfile", "ParticipantProfile")
                        .WithMany()
                        .HasForeignKey("ParticipantProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamDraft.Api.Entities.Team", "Team")
                        .WithMany("Picks")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParticipantProfile");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.Team", b =>
                {
                    b.HasOne("TeamDraft.Api.Entities.User", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.Team", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("Picks");
                });

            modelBuilder.Entity("TeamDraft.Api.Entities.User", b =>
                {
                    b.Navigation("ParticipantProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
